import { useShallow } from 'zustand/react/shallow';
import { useWallpaperStore } from '@/store/wallpaperStore';

export function useBackgroundStore() {
	return useWallpaperStore(
		useShallow(s => ({
			backgroundImages: s.backgroundImages,
			setlists: s.setlists,
			activeSetlistId: s.activeSetlistId,
			activeImageId: s.activeImageId,
			imageIds: s.imageIds,
			imageFitMode: s.imageFitMode,
			imageScale: s.imageScale,
			imagePositionX: s.imagePositionX,
			imagePositionY: s.imagePositionY,
			imageFocusX: s.imageFocusX,
			imageFocusY: s.imageFocusY,
			imageOpacity: s.imageOpacity,
			imageMirror: s.imageMirror,
			imageMirrorFill: s.imageMirrorFill,
			imageMirrorFillInvert: s.imageMirrorFillInvert,
			imageMirrorFillCount: s.imageMirrorFillCount,
			imageCoverageLockEnabled: s.imageCoverageLockEnabled,
			imageRotation: s.imageRotation,
			slideshowTransitionType: s.slideshowTransitionType,
			slideshowTransitionDuration: s.slideshowTransitionDuration,
			slideshowTransitionIntensity: s.slideshowTransitionIntensity,
			slideshowTransitionAudioDrive: s.slideshowTransitionAudioDrive,
			slideshowTransitionAudioChannel: s.slideshowTransitionAudioChannel,
			slideshowTransitionAudioSmoothing:
				s.slideshowTransitionAudioSmoothing,
			slideshowManualTimestampsEnabled:
				s.slideshowManualTimestampsEnabled,
			globalBackgroundId: s.globalBackgroundId,
			globalBackgroundUrl: s.globalBackgroundUrl,
			globalBackgroundEnabled: s.globalBackgroundEnabled,
			globalBackgroundFitMode: s.globalBackgroundFitMode,
			globalBackgroundScale: s.globalBackgroundScale,
			globalBackgroundPositionX: s.globalBackgroundPositionX,
			globalBackgroundPositionY: s.globalBackgroundPositionY,
			globalBackgroundOpacity: s.globalBackgroundOpacity,
			globalBackgroundBrightness: s.globalBackgroundBrightness,
			globalBackgroundContrast: s.globalBackgroundContrast,
			globalBackgroundSaturation: s.globalBackgroundSaturation,
			globalBackgroundBlur: s.globalBackgroundBlur,
			globalBackgroundHueRotate: s.globalBackgroundHueRotate,
			layoutResponsiveEnabled: s.layoutResponsiveEnabled,
			layoutBackgroundReframeEnabled: s.layoutBackgroundReframeEnabled,
			layoutReferenceWidth: s.layoutReferenceWidth,
			layoutReferenceHeight: s.layoutReferenceHeight,
			editorImagePreviewQuality: s.editorImagePreviewQuality,
			setImageThumbnailUrl: s.setImageThumbnailUrl,
			setGlobalBackgroundId: s.setGlobalBackgroundId,
			setGlobalBackgroundUrl: s.setGlobalBackgroundUrl,
			addImageEntry: s.addImageEntry,
			setActiveImageId: s.setActiveImageId,
			setSetlistImages: s.setSetlistImages,
			setBackgroundImageEntryEnabled: s.setBackgroundImageEntryEnabled,
			moveImageEntryToIndex: s.moveImageEntryToIndex,
			removeImageEntry: s.removeImageEntry,
			setImageUrls: s.setImageUrls,
			setImageFitMode: s.setImageFitMode,
			setImageScale: s.setImageScale,
			setImagePositionX: s.setImagePositionX,
			setImagePositionY: s.setImagePositionY,
			setImageFocusPoint: s.setImageFocusPoint,
			setImageRotation: s.setImageRotation,
			setImageOpacity: s.setImageOpacity,
			setImageMirror: s.setImageMirror,
			setImageMirrorFill: s.setImageMirrorFill,
			setImageMirrorFillInvert: s.setImageMirrorFillInvert,
			setImageMirrorFillCount: s.setImageMirrorFillCount,
			setImageCoverageLockEnabled: s.setImageCoverageLockEnabled,
			setSlideshowTransitionType: s.setSlideshowTransitionType,
			setSlideshowTransitionDuration: s.setSlideshowTransitionDuration,
			setSlideshowTransitionIntensity: s.setSlideshowTransitionIntensity,
			setSlideshowTransitionAudioDrive:
				s.setSlideshowTransitionAudioDrive,
			setSlideshowTransitionAudioChannel:
				s.setSlideshowTransitionAudioChannel,
			setSlideshowTransitionAudioSmoothing:
				s.setSlideshowTransitionAudioSmoothing,
			captureImageLogoOverride: s.captureImageLogoOverride,
			setImageLogoOverride: s.setImageLogoOverride,
			captureImageSpectrumOverride: s.captureImageSpectrumOverride,
			setImageSpectrumOverride: s.setImageSpectrumOverride,
			captureImageParticlesOverride: s.captureImageParticlesOverride,
			setImageParticlesOverride: s.setImageParticlesOverride,
			captureImageRainOverride: s.captureImageRainOverride,
			setImageRainOverride: s.setImageRainOverride,
			captureImageLooksOverride: s.captureImageLooksOverride,
			setImageLooksOverride: s.setImageLooksOverride,
			setBackgroundImagePlaybackSwitchAt:
				s.setBackgroundImagePlaybackSwitchAt,
			moveImageEntry: s.moveImageEntry,
			shuffleImageEntries: s.shuffleImageEntries,
			autoFitAllImages: s.autoFitAllImages,
			autoFitCoveredActiveImage: s.autoFitCoveredActiveImage,
			autoFocusActiveImage: s.autoFocusActiveImage,
			autoFocusAllImages: s.autoFocusAllImages,
			autoPlaceLogoForActiveImage: s.autoPlaceLogoForActiveImage,
			setActiveImageFramingEdited: s.setActiveImageFramingEdited,
			setGlobalBackgroundEnabled: s.setGlobalBackgroundEnabled,
			setGlobalBackgroundFitMode: s.setGlobalBackgroundFitMode,
			setGlobalBackgroundScale: s.setGlobalBackgroundScale,
			setGlobalBackgroundPositionX: s.setGlobalBackgroundPositionX,
			setGlobalBackgroundPositionY: s.setGlobalBackgroundPositionY,
			setGlobalBackgroundOpacity: s.setGlobalBackgroundOpacity,
			setGlobalBackgroundBrightness: s.setGlobalBackgroundBrightness,
			setGlobalBackgroundContrast: s.setGlobalBackgroundContrast,
			setGlobalBackgroundSaturation: s.setGlobalBackgroundSaturation,
			setGlobalBackgroundBlur: s.setGlobalBackgroundBlur,
			setGlobalBackgroundHueRotate: s.setGlobalBackgroundHueRotate
		}))
	);
}

export type BackgroundStore = ReturnType<typeof useBackgroundStore>;
