import type { WallpaperState } from '@/types/wallpaper';
import {
	createDefaultBackgroundProfileSlots,
	createDefaultLogoProfileSlots,
	createDefaultCameraFxProfileSlots,
	createDefaultLightsProfileSlots,
	createDefaultLooksProfileSlots,
	createDefaultParticlesProfileSlots,
	createDefaultRainProfileSlots,
	createDefaultSpectrumProfileSlots,
	createDefaultSpectrumSecondProfileSlots,
	createDefaultTrackTitleProfileSlots
} from '@/store/featureProfiles';
import { IMAGE_BASS_ZOOM_CLASSIC } from '@/features/presets/imageBassZoomProfiles';
import { createDefaultCalibrationProfileSlots } from '@/features/calibration';
import { getCurrentViewportResolution } from '@/features/layout/viewportMetrics';
import { DEFAULT_SPECTRUM_STATE } from '@/features/spectrum';

// Re-exported so existing importers keep working; the constant itself lives
// in `config/` because the renderer (a feature) may not import the store.
import { APP_LOGO_URL } from '@/config/appLogo';
export { APP_LOGO_URL };

/**
 * Curated starter palette for the global color-favourites strip. A balanced
 * spread of clean whites, cool cyans/teals, warm golds, and refined
 * rose/amethyst tones — all bright enough to read as text/glow accents over
 * busy wallpapers while staying tasteful. Seeded on fresh installs and for
 * existing users whose favourites list is still empty.
 */
export const DEFAULT_COLOR_FAVORITES: string[] = [
	'#ffffff', // pure white
	'#f5f5f5', // soft white
	'#38bdf8', // sky blue
	'#04d9ff', // electric cyan
	'#2dd4bf', // teal
	'#34d399', // emerald
	'#fbbf24', // amber
	'#d4af37', // metallic gold
	'#fb923c', // warm orange
	'#fb7185', // coral rose
	'#f472b6', // pink
	'#b76e79', // rose gold
	'#a855f7', // amethyst
	'#818cf8' // indigo
];

const initialLayoutReference = getCurrentViewportResolution();

export const DEFAULT_STATE: WallpaperState = {
	// Background FX
	noiseIntensity: 0.0,
	rgbShift: 0.003,
	scanlinesEnabled: true,
	scanlineIntensity: 0.12,
	scanlineMode: 'always',
	scanlineSpacing: 800,
	scanlineThickness: 1.2,
	parallaxStrength: 0.03,
	backgroundImageEnabled: true,
	imageUrl: null,
	imageScale: 1.0,
	imagePositionX: 0.0,
	imagePositionY: 0.0,
	imageFocusX: null,
	imageFocusY: null,
	imageOpacity: 1,
	imageBassReactive: false,
	imageBassScaleIntensity: 0.5,
	imageAudioReactiveDecay: 0.62,
	imageAudioSmoothing: 0.18,
	imageOpacityReactive: false,
	imageOpacityReactiveAmount: 0.35,
	imageOpacityReactiveInvert: false,
	imageOpacityReactiveThreshold: 0.7,
	imageOpacityReactiveSoftness: 0.22,
	imageBlurReactive: false,
	imageBlurReactiveAmount: 0,
	imageBlurReactiveInvert: false,
	imageBlurReactiveThreshold: 0.74,
	imageBlurReactiveSoftness: 0.14,
	...IMAGE_BASS_ZOOM_CLASSIC,
	imageBassZoomPresetId: 'classic',
	imageAudioChannel: 'kick',
	backgroundProfileSlots: createDefaultBackgroundProfileSlots(),
	imageFitMode: 'contain',
	imageMirror: false,
	imageMirrorFill: false,
	imageMirrorFillInvert: false,
	imageMirrorFillCount: 1,
	imageRotation: 0,
	showBackgroundScaleMeter: false,
	showAutoZoomDebug: false,
	showSpectrumDiagnosticsHud: false,
	showLogoDiagnosticsHud: false,
	diagnosticsHudPositionX: 0.02,
	diagnosticsHudPositionY: 0.06,
	filterTargets: ['background'],
	filterOpacity: 1,
	sceneServiceBaseUrl: '',
	filterBrightness: 1,
	filterContrast: 1,
	filterSaturation: 1,
	filterBlur: 0,
	filterHueRotate: 0,
	filterVignette: 0,
	filterBloom: 0,
	filterLumaThreshold: 0.72,
	filterLensWarp: 0,
	filterHeatDistortion: 0,
	activeFilterLookId: null,
	customFilterLookSettings: null,
	globalBackgroundEnabled: true,
	globalBackgroundId: null,
	globalBackgroundUrl: null,
	globalBackgroundScale: 1,
	globalBackgroundPositionX: 0,
	globalBackgroundPositionY: 0,
	globalBackgroundFitMode: 'cover',
	globalBackgroundOpacity: 1,
	globalBackgroundBrightness: 1,
	globalBackgroundContrast: 1,
	globalBackgroundSaturation: 1,
	globalBackgroundBlur: 0,
	globalBackgroundHueRotate: 0,

	rgbShiftAudioReactive: false,
	rgbShiftAudioSensitivity: 0.008,
	rgbShiftAudioChannel: 'hihat',
	rgbShiftAudioSmoothing: 0.18,
	rgbShiftAudioAttack: 0.55,
	rgbShiftAudioRelease: 0.15,
	rgbShiftAudioReactivitySpeed: 1.0,
	rgbShiftAudioPeakWindow: 1.0,
	rgbShiftAudioPeakFloor: 0.08,
	rgbShiftAudioPunch: 0.3,

	// Audio
	audioReactive: false,
	audioSensitivity: 1.0,
	audioCaptureState: 'idle',
	audioSourceMode: 'none',
	audioFileAssetId: null,
	audioFileName: '',
	audioFileVolume: 1,
	audioFileLoop: true,
	audioPaused: false,
	motionPaused: false,
	fftSize: 2048,
	audioSmoothing: 0.8,
	audioChannelSmoothing: 0.42,
	audioAutoKickThreshold: 0.08,
	audioAutoSwitchHoldMs: 180,
	audioTracks: [],
	activeAudioTrackId: null,
	queuedAudioTrackId: null,
	audioCrossfadeEnabled: false,
	audioCrossfadeSeconds: 3,
	audioAutoAdvance: true,
	audioMixMode: 'sequential',
	audioTransitionStyle: 'linear',
	mediaSessionEnabled: false,
	trackMetadataMode: 'auto',
	trackMetadataAutoSource: 'name',
	nowPlayingMode: 'widget',
	nowPlayingCoverEnabled: false,
	nowPlayingArtistEnabled: true,
	nowPlayingProgressEnabled: true,
	nowPlayingScale: 1,
	nowPlayingAccentColor: '#00eaff',
	nowPlayingAccentColorSource: 'manual',
	nowPlayingTextTreatment: 'solid',
	trackManualArtist: '',
	trackManualTitle: '',
	audioTrackTitleEnabled: false,
	audioTrackTitleLayoutMode: 'centered',
	audioTrackTitleFontStyle: 'techno',
	audioTrackTitleUppercase: false,
	audioTrackTitlePositionX: 0,
	audioTrackTitlePositionY: -0.76,
	audioTrackTitleFontSize: 28,
	audioTrackTitleLetterSpacing: 0,
	audioTrackTitleWidth: 0.42,
	audioTrackTitleOpacity: 0.95,
	audioTrackTitleScrollSpeed: 42,
	audioTrackTitleRgbShift: 0,
	audioTrackTitleTextColor: '#f8fafc',
	audioTrackTitleTextColorSource: 'manual',
	audioTrackTitleStrokeColor: '#020617',
	audioTrackTitleStrokeColorSource: 'manual',
	audioTrackTitleStrokeWidth: 2.2,
	audioTrackTitleGlowColor: '#00eaff',
	audioTrackTitleGlowColorSource: 'manual',
	audioTrackTitleGlowBlur: 18,
	audioTrackTitleGlowReach: 1,
	audioTrackTitleBackdropEnabled: true,
	audioTrackTitleBackdropColor: '#020617',
	audioTrackTitleBackdropColorSource: 'manual',
	audioTrackTitleBackdropOpacity: 0.5,
	audioTrackTitleBackdropPadding: 12,
	audioTrackTitleFilterBrightness: 1,
	audioTrackTitleFilterContrast: 1,
	audioTrackTitleFilterSaturation: 1,
	audioTrackTitleFilterBlur: 0,
	audioTrackTitleFilterHueRotate: 0,
	audioTrackTimeEnabled: false,
	audioTrackTimePositionX: 0,
	audioTrackTimePositionY: -0.66,
	audioTrackTimeWidth: 0.3,
	audioTrackTimeFontStyle: 'mono',
	audioTrackTimeFontSize: 18,
	audioTrackTimeLetterSpacing: 0.4,
	audioTrackTimeOpacity: 0.92,
	audioTrackTimeRgbShift: 0,
	audioTrackTimeTextColor: '#7dd3fc',
	audioTrackTimeTextColorSource: 'manual',
	audioTrackTimeStrokeColor: '#082f49',
	audioTrackTimeStrokeColorSource: 'manual',
	audioTrackTimeStrokeWidth: 1.8,
	audioTrackTimeGlowColor: '#00eaff',
	audioTrackTimeGlowColorSource: 'manual',
	audioTrackTimeGlowBlur: 12,
	audioTrackTimeGlowReach: 1,
	audioTrackTimeFilterBrightness: 1,
	audioTrackTimeFilterContrast: 1,
	audioTrackTimeFilterSaturation: 1,
	audioTrackTimeFilterBlur: 0,
	audioTrackTimeFilterHueRotate: 0,
	audioLyricsEnabled: false,
	audioLyricsLayoutMode: 'centered',
	audioLyricsUppercase: false,
	audioLyricsPositionX: 0,
	audioLyricsPositionY: 0.58,
	audioLyricsWidth: 0.62,
	audioLyricsFontStyle: 'clean',
	audioLyricsFontSize: 34,
	audioLyricsLetterSpacing: 0.2,
	audioLyricsLineHeight: 1.28,
	audioLyricsVisibleLineCount: 3,
	audioLyricsShowTranslation: true,
	audioLyricsOpacity: 1,
	audioLyricsInactiveOpacity: 0.38,
	audioLyricsTimeOffsetMs: 0,
	audioLyricsActiveColor: '#f8fafc',
	audioLyricsActiveColorSource: 'manual',
	audioLyricsActiveColorMode: 'solid',
	audioLyricsActiveColorSecondary: '#000000',
	audioLyricsInactiveColor: '#94a3b8',
	audioLyricsInactiveColorSource: 'manual',
	audioLyricsTextTreatment: 'solid',
	audioLyricsStrokeColor: '#020617',
	audioLyricsStrokeColorSource: 'manual',
	audioLyricsStrokeColorMode: 'solid',
	audioLyricsStrokeColorSecondary: '#ffffff',
	audioLyricsStrokeWidth: 1.6,
	audioLyricsGlowColor: '#22d3ee',
	audioLyricsGlowColorSource: 'manual',
	audioLyricsGlowColorMode: 'solid',
	audioLyricsGlowColorSecondary: '#ffffff',
	audioLyricsGlowBlur: 20,
	audioLyricsGlowReach: 1,
	audioLyricsTransitionIn: 'fade',
	audioLyricsTransitionOut: 'fade',
	audioLyricsActiveAnimation: 'none',
	audioLyricsAnimationDurationMs: 220,
	audioLyricsBackdropEnabled: true,
	audioLyricsBackdropColor: '#020617',
	audioLyricsBackdropColorSource: 'manual',
	audioLyricsBackdropColorMode: 'solid',
	audioLyricsBackdropColorSecondary: '#ffffff',
	audioLyricsBackdropFollowAnimation: true,
	audioLyricsBackdropOpacity: 0.42,
	audioLyricsBackdropPadding: 18,
	audioLyricsBackdropRadius: 18,
	audioLyricsByTrackAssetId: {},

	// Spectrum — the domain owns its factory defaults; only the profile
	// slots stay here, because store/featureProfiles builds them.
	...DEFAULT_SPECTRUM_STATE,
	spectrumProfileSlots: createDefaultSpectrumProfileSlots(),
	spectrumSecondProfileSlots: createDefaultSpectrumSecondProfileSlots(),

	// Logo
	logoEnabled: true,
	logoUrl: APP_LOGO_URL,
	logoVariantMode: 'auto',
	logoBaseSize: 80,
	logoPositionX: 0,
	logoPositionY: 0,
	logoCircularCrop: false,
	logoCropRadius: 1,
	logoBandMode: 'kick',
	logoAudioSmoothing: 0.18,
	logoAudioSensitivity: 3.8,
	logoReactiveScaleIntensity: 0.9,
	logoReactivitySpeed: 0.68,
	logoAttack: 0.95,
	logoRelease: 0.05,
	logoMinScale: 1,
	logoMaxScale: 1.85,
	logoPunch: 0.4,
	logoPeakWindow: 1.9,
	logoPeakFloor: 0.1,
	logoGlowEnabled: true,
	logoGlowColor: '#00ffff',
	logoGlowColorSource: 'manual',
	logoGlowBlur: 30,
	logoGlowReach: 1,
	logoGlowAudioAmount: 0,
	logoShadowEnabled: true,
	logoShadowColor: '#00ffff',
	logoShadowColorSource: 'manual',
	logoShadowBlur: 40,
	logoBackdropEnabled: true,
	logoBackdropColor: '#000000',
	logoBackdropColorSource: 'manual',
	logoBackdropOpacity: 0.5,
	logoBackdropPadding: 20,
	logoRotationSpeed: 0,
	logoProfileSlots: createDefaultLogoProfileSlots(),

	// Particles
	particlesEnabled: true,
	particleLayerMode: 'both',
	particleShape: 'circles',
	particleColor1: '#00ffff',
	particleColor2: '#ff00ff',
	particleColorSource: 'manual',
	particleColorMode: 'gradient',
	particleSizeMin: 3,
	particleSizeMax: 10,
	particleOpacity: 0.7,
	particleGlow: true,
	particleGlowStrength: 0.6,
	particleGlowReach: 1,
	particleGlowAudioAmount: 0,
	particleFilterBrightness: 1,
	particleFilterContrast: 1,
	particleFilterSaturation: 1,
	particleFilterBlur: 0,
	particleFilterHueRotate: 0,
	particleRotationIntensity: 0,
	particleRotationDirection: 'clockwise',
	particleFadeInOut: true,
	particleAudioReactive: true,
	particleAudioChannel: 'instrumental',
	particleAudioSmoothing: 0.18,
	particleAudioSizeBoost: 2.0,
	particleAudioOpacityBoost: 0.3,
	particleAudioAttack: 0.65,
	particleAudioRelease: 0.18,
	particleAudioReactivitySpeed: 1.0,
	particleAudioPeakWindow: 1.2,
	particleAudioPeakFloor: 0.06,
	particleAudioPunch: 0.2,
	particleAudioDriftEnabled: false,
	particleAudioDriftAngle: 0,
	particleAudioDriftAmount: 0.45,
	particleAudioDriftBase: 0,
	particleAudioDriftChannel: 'kick',
	particleAudioDriftThreshold: 0.35,
	particleAudioDriftRelease: 0.18,
	particleAudioDriftMode: 'velocity',
	particleAudioDriftInvertOnLowEnergy: false,
	particleDepthFlowEnabled: false,
	particleDepthFlowAmount: 0.65,
	particleDepthFlowDirection: 'towardViewer',
	particleDepthFlowChannel: 'kick',
	particleDepthFlowThreshold: 0.38,
	particleDepthFlowSensitivity: 1,
	particleDepthFlowAttack: 0.55,
	particleDepthFlowRelease: 0.22,
	particleDepthFlowSpeed: 0.8,
	particleDepthFlowSpread: 1,
	particleDepthFlowFocusX: 0.5,
	particleDepthFlowFocusY: 0.5,
	particleDepthFlowMode: 'pullToCamera',
	particleDepthFlowSpawnOrigin: 'fromFocus',
	particleDepthFlowInvertFocusOnLowEnergy: false,
	particleDepthFlowInvertFocusAxis: 'both',
	particleDepthFlowWindInfluence: 0.35,
	particleCount: 60,
	particleSpeed: 0.5,
	particleLifetime: 1.0,

	// Rain
	rainEnabled: false,
	rainIntensity: 0.5,
	rainDropCount: 50,
	rainAngle: 10,
	rainMeshRotationZ: 0,
	rainColor: '#a0c8ff',
	rainColorSource: 'manual',
	rainColorMode: 'solid',
	rainParticleType: 'lines',
	rainLength: 0.12,
	rainWidth: 0.0015,
	rainBlur: 0.002,
	rainSpeed: 0.8,
	rainVariation: 0.35,
	particlesProfileSlots: createDefaultParticlesProfileSlots(),
	rainProfileSlots: createDefaultRainProfileSlots(),
	looksProfileSlots: createDefaultLooksProfileSlots(),
	lightsProfileSlots: createDefaultLightsProfileSlots(),
	cameraFxProfileSlots: createDefaultCameraFxProfileSlots(),
	trackTitleProfileSlots: createDefaultTrackTitleProfileSlots(),
	sceneSlots: [],
	activeSceneSlotId: null,
	defaultSceneSlotId: null,
	setlists: [],
	activeSetlistId: null,
	showSetlistHud: true,
	calibrationRangeOverrides: {},
	calibrationProfileSlots: createDefaultCalibrationProfileSlots(),
	calibrationSyntheticGroups: {},

	// Stage Lights FX (Task 2)
	stageLightsEnabled: false,
	stageLightsIntensity: 0.6,
	stageLightsBeamCount: 5,
	stageLightsMinBeamCount: 3,
	stageLightsMaxBeamCount: 5,
	stageLightsBeamWidth: 0.4,
	stageLightsBeamLength: 0.95,
	stageLightsSoftness: 0.5,
	stageLightsSpeed: 0.5,
	stageLightsFixedMotion: true,
	stageLightsColorSource: 'theme',
	stageLightsColor: '#ff3df0',
	stageLightsAudioReactive: true,
	stageLightsAudioChannel: 'kick',
	stageLightsAudioAmount: 0.8,
	stageLightsAudioOscillationAmount: 1,
	stageLightsAudioHoldMs: 90,
	stageLightsAudioDecay: 0.82,
	stageLightsAudioGateEnabled: true,
	stageLightsPeakFlash: true,
	stageLightsPeakThreshold: 0.6,
	stageLightsBandThresholds: { kick: 0.32, bass: 0.42, full: 0.28 },
	stageLightsOpacity: 0.5,
	stageLightsBlendMode: 'lighter',
	stageLightsOrigin: 'top',
	stageLightsMovementMode: 'top-down',
	stageLightsInvertDirection: false,
	stageLightsMirrorDirections: false,

	// Flash Light FX. Defaults preserve the old peak flash look only when the
	// layer is explicitly enabled; migrations carry existing peak flash users.
	flashLightEnabled: false,
	flashLightIntensity: 0.42,
	flashLightColorSource: 'theme',
	flashLightColor: '#ffffff',
	flashLightSoftness: 0.45,
	flashLightBrightness: 1.1,
	flashLightDecay: 2.2,
	flashLightAudioChannel: 'kick',
	flashLightThreshold: 0.68,
	flashLightBandThresholds: { kick: 0.5, bass: 0.6, full: 0.68 },
	flashLightSensitivity: 1,
	flashLightRetriggerMs: 110,
	flashLightShape: 'center-bloom',
	flashLightBlendMode: 'screen',

	// Logo Flash Edge
	logoFlashEdgeEnabled: false,
	logoFlashEdgeIntensityMult: 1.2,
	logoFlashEdgeThickness: 3,
	logoFlashEdgeRadius: 24,
	logoFlashEdgeColorMode: 'flash',
	logoFlashEdgeColor: '#00eeff',

	// Background Flash Edge
	bgFlashEdgeEnabled: false,
	bgFlashEdgeIntensityMult: 1.0,
	bgFlashEdgeThickness: 4,
	bgFlashEdgeRadius: 28,
	bgFlashEdgeColorMode: 'flash',
	bgFlashEdgeColor: '#ff00cc',

	// Camera FX (Task 3)
	cameraFxEnabled: false,
	cameraMotionEnabled: false,
	cameraMotionMode: 'none',
	cameraMotionAmount: 0.3,
	cameraMotionSpeed: 0.4,
	cameraMotionDrive: 'fixed-audio',
	cameraMotionAudioInfluence: 0.3,
	cameraMotionAudioChannel: 'full',
	cameraMotionDirection: 'cw',
	cameraMotionTarget: 'background',
	cameraMotionTargets: ['background'],
	cameraShakeEnabled: false,
	cameraShakeAmount: 0.5,
	cameraShakeDecay: 0.85,
	cameraShakeThreshold: 0.6,
	cameraShakeBandThresholds: { kick: 0.28, bass: 0.46, full: 0.58 },
	cameraShakeTargets: [
		'global-background',
		'background',
		'selected-overlay',
		'logo',
		'spectrum',
		'particles',
		'rain',
		'track-title',
		'lyrics',
		'stage-lights',
		'flash-light'
	],
	cameraShakeSensitivity: 1.4,
	cameraShakeRetriggerMs: 100,
	cameraShakeChannel: 'kick',
	cameraShakeMode: 'free',
	cameraShakeFrequency: 16,
	cameraShakeRoughness: 0.75,

	// Slideshow
	slideshowEnabled: false,
	slideshowInterval: 30,
	slideshowTransitionDuration: 1.0,
	slideshowTransitionType: 'fade' as const,
	slideshowTransitionIntensity: 1,
	slideshowTransitionAudioDrive: 0,
	slideshowTransitionAudioChannel: 'instrumental',
	slideshowTransitionAudioSmoothing: 0,
	slideshowResetPosition: false,
	slideshowAudioCheckpointsEnabled: false,
	slideshowTrackChangeSyncEnabled: false,
	slideshowManualTimestampsEnabled: false,
	activeImageId: null,
	visualTransition: null,
	backgroundImages: [],
	imageUrls: [],

	// Persistence
	imageIds: [],
	logoId: null,
	overlays: [],
	selectedOverlayId: null,

	// Responsive Layout
	layoutResponsiveEnabled: true,
	layoutBackgroundReframeEnabled: true,
	layoutReferenceWidth: initialLayoutReference.width,
	layoutReferenceHeight: initialLayoutReference.height,
	editorSidebarCollapsed: false,

	// System
	performanceMode: 'medium',
	customPresets: {},
	activePreset: 'custom:session',
	language: 'en',
	isPresetDirty: false,
	showFps: true,
	controlPanelAnchor: 'bottom-right',
	controlPanelOffsetX: 0,
	controlPanelOffsetY: 0,
	hudLiquidGlassEnabled: false,
	quickEditCaptureMode: 'selection',
	colorFavorites: DEFAULT_COLOR_FAVORITES,
	controlPanelActiveTab: null,
	activeSpectrumTarget: 'main',
	fpsOverlayAnchor: 'top-left',
	editorTheme: 'glass',
	editorThemeColorSource: 'theme',
	editorCornerRadius: 10,
	editorControlCornerRadius: 10,
	editorUiScale: 1,
	editorShowPreciseNumericControls: false,
	editorCompactSlotIcons: false,
	editorManualAccentColor: '#ffffff',
	editorManualSecondaryColor: '#67e8f9',
	editorManualBackdropColor: '#0b1120',
	editorManualTextPrimaryColor: '#ffffff',
	editorManualTextSecondaryColor: '#cbd5e1',
	editorManualBackdropOpacity: 0.84,
	editorManualBlurPx: 18,
	editorManualSurfaceOpacity: 0.34,
	editorManualItemOpacity: 0.28,
	editorImagePreviewQuality: 'optimized' as const,
	quickActionsEnabled: true,
	// Normalized 0–1: 0 = left/top edge (+ margin), 1 = right/bottom edge (+ margin)
	quickActionsPositionX: 1.0,
	quickActionsPositionY: 1.0,
	quickActionsLauncherPositionX: 1.0,
	quickActionsLauncherPositionY: 1.0,
	quickActionsBackdropOpacity: 0.34,
	quickActionsBlurPx: 20,
	quickActionsScale: 1.0,
	quickActionsLauncherSize: 64,
	quickActionsColorSource: 'theme',
	quickActionsManualAccentColor: '#ffffff',
	quickActionsManualSecondaryColor: '#67e8f9',
	quickActionsManualBackdropColor: '#0b1120',
	quickActionsManualTextPrimaryColor: '#ffffff',
	quickActionsManualTextSecondaryColor: '#cbd5e1',
	quickActionsManualSurfaceOpacity: 0.3,
	quickActionsManualItemOpacity: 0.2,
	layerZIndices: {},
	sleepModeEnabled: true,
	sleepModeDelaySeconds: 45,
	sleepModeActive: false,
	virtualFoldersEnabled: true,

	discoveryOnboardingDismissed: false,
	performanceSafeEnabled: false,
	performanceModeBeforeSafe: null,

	// Design mode
	uiMode: 'simple' as const,
	enableDragMode: false,
	activeTool: 'none' as const
};

export const PARTICLE_LIMITS: Record<string, number> = {
	low: 20,
	medium: 80,
	high: 200
};
