import { DEFAULT_STATE } from '@/store/defaultState';
import type {
	CustomPresetsMap,
	Preset,
	PresetKey,
	PresetsMap
} from '@/types/presets';
import type { WallpaperState } from '@/types/wallpaper';

export const presets: PresetsMap = {
	softDream: {
		filterTargets: ['background'],
		filterOpacity: 1,
		filterBrightness: 1,
		filterContrast: 1,
		filterSaturation: 1,
		filterBlur: 0,
		filterHueRotate: 0,
		rgbShift: 0.001,
		scanlineIntensity: 0.06,
		scanlineMode: 'pulse',
		scanlineSpacing: 720,
		scanlineThickness: 1.1,
		parallaxStrength: 0.02,
		spectrumEnabled: true,
		spectrumInnerRadius: 70,
		spectrumBarCount: 96,
		spectrumBarWidth: 2,
		spectrumMinHeight: 2,
		spectrumMaxHeight: 80,
		spectrumOpacity: 0.7,
		spectrumGlowIntensity: 0.5,
		spectrumShadowBlur: 12,
		spectrumPrimaryColor: '#c084fc',
		spectrumSecondaryColor: '#f9a8d4',
		spectrumColorSource: 'manual',
		spectrumColorMode: 'gradient',
		spectrumBandMode: 'full',
		spectrumShape: 'wave',
		spectrumMode: 'radial',
		spectrumLinearOrientation: 'horizontal',
		spectrumRadialShape: 'circle',
		spectrumRadialAngle: 0,
		spectrumMirror: true,
		spectrumPeakHold: false,
		spectrumPeakDecay: 0.004,
		spectrumRotationSpeed: 0.1,
		spectrumSmoothing: 0.85,
		logoEnabled: false,
		logoBaseSize: 70,
		logoPositionX: 0,
		logoPositionY: 0,
		logoBandMode: 'kick',
		logoReactiveScaleIntensity: 0.25,
		logoReactivitySpeed: 0.1,
		logoAttack: 0.55,
		logoRelease: 0.07,
		logoMinScale: 1,
		logoMaxScale: 1.4,
		logoPunch: 0.18,
		logoPeakWindow: 2.6,
		logoPeakFloor: 0.22,
		logoGlowColor: '#c084fc',
		logoGlowColorSource: 'manual',
		logoGlowBlur: 20,
		logoShadowEnabled: true,
		logoShadowColor: '#c084fc',
		logoShadowColorSource: 'manual',
		logoShadowBlur: 30,
		logoBackdropEnabled: true,
		logoBackdropColor: '#1a0030',
		logoBackdropColorSource: 'manual',
		logoBackdropOpacity: 0.4,
		logoBackdropPadding: 16,
		particlesEnabled: true,
		particleLayerMode: 'both',
		particleColor1: '#c084fc',
		particleColor2: '#f9a8d4',
		particleColorSource: 'manual',
		particleColorMode: 'gradient',
		particleSizeMin: 1,
		particleSizeMax: 2,
		particleOpacity: 0.5,
		particleGlow: true,
		particleGlowStrength: 0.4,
		particleFilterBrightness: 1,
		particleFilterContrast: 1,
		particleFilterSaturation: 1,
		particleFilterBlur: 0,
		particleFilterHueRotate: 0,
		particleRotationIntensity: 0.5,
		particleRotationDirection: 'clockwise',
		particleFadeInOut: true,
		particleAudioReactive: false,
		particleAudioSizeBoost: 1.0,
		particleAudioOpacityBoost: 0.1,
		particleCount: 40,
		particleSpeed: 0.3,
		rainEnabled: false,
		rainIntensity: 0.0,
		rainDropCount: 40,
		rainAngle: 5,
		rainMeshRotationZ: 0,
		rainColor: '#d4b8f0',
		rainColorSource: 'manual',
		rainColorMode: 'solid',
		rainParticleType: 'dots',
		rainLength: 0.05,
		rainWidth: 0.002,
		rainBlur: 0.003,
		rainSpeed: 0.4,
		rainVariation: 0.2,
		performanceMode: 'medium',
		audioSensitivity: 0.8,
		audioSmoothing: 0.9
	},

	cyberPop: {
		filterTargets: ['background'],
		filterOpacity: 1,
		filterBrightness: 1,
		filterContrast: 1,
		filterSaturation: 1,
		filterBlur: 0,
		filterHueRotate: 0,
		rgbShift: 0.006,
		scanlineIntensity: 0.18,
		scanlineMode: 'burst',
		scanlineSpacing: 900,
		scanlineThickness: 1.4,
		parallaxStrength: 0.04,
		spectrumEnabled: true,
		spectrumInnerRadius: 85,
		spectrumBarCount: 128,
		spectrumBarWidth: 2,
		spectrumMinHeight: 2,
		spectrumMaxHeight: 130,
		spectrumOpacity: 0.95,
		spectrumGlowIntensity: 1.0,
		spectrumShadowBlur: 22,
		spectrumPrimaryColor: '#00ffff',
		spectrumSecondaryColor: '#ff00ff',
		spectrumColorSource: 'manual',
		spectrumColorMode: 'gradient',
		spectrumBandMode: 'full',
		spectrumShape: 'bars',
		spectrumMode: 'radial',
		spectrumLinearOrientation: 'horizontal',
		spectrumRadialShape: 'circle',
		spectrumRadialAngle: 0,
		spectrumMirror: true,
		spectrumPeakHold: true,
		spectrumPeakDecay: 0.003,
		spectrumRotationSpeed: 0,
		spectrumSmoothing: 0.75,
		logoEnabled: false,
		logoBaseSize: 90,
		logoPositionX: 0,
		logoPositionY: 0,
		logoBandMode: 'kick',
		logoReactiveScaleIntensity: 0.5,
		logoReactivitySpeed: 0.35,
		logoAttack: 0.9,
		logoRelease: 0.12,
		logoMinScale: 1,
		logoMaxScale: 1.9,
		logoPunch: 0.42,
		logoPeakWindow: 2.1,
		logoPeakFloor: 0.16,
		logoGlowColor: '#00ffff',
		logoGlowColorSource: 'manual',
		logoGlowBlur: 35,
		logoShadowEnabled: true,
		logoShadowColor: '#ff00ff',
		logoShadowColorSource: 'manual',
		logoShadowBlur: 50,
		logoBackdropEnabled: true,
		logoBackdropColor: '#000010',
		logoBackdropColorSource: 'manual',
		logoBackdropOpacity: 0.6,
		logoBackdropPadding: 22,
		particlesEnabled: true,
		particleLayerMode: 'both',
		particleColor1: '#00ffff',
		particleColor2: '#ff00ff',
		particleColorSource: 'manual',
		particleColorMode: 'gradient',
		particleSizeMin: 1,
		particleSizeMax: 3,
		particleOpacity: 0.75,
		particleGlow: true,
		particleGlowStrength: 0.8,
		particleFilterBrightness: 1,
		particleFilterContrast: 1,
		particleFilterSaturation: 1,
		particleFilterBlur: 0,
		particleFilterHueRotate: 0,
		particleRotationIntensity: 1.2,
		particleRotationDirection: 'clockwise',
		particleFadeInOut: true,
		particleAudioReactive: true,
		particleAudioSizeBoost: 2.5,
		particleAudioOpacityBoost: 0.35,
		particleCount: 80,
		particleSpeed: 0.7,
		rainEnabled: false,
		rainIntensity: 0.0,
		rainDropCount: 50,
		rainAngle: 10,
		rainMeshRotationZ: 0,
		rainColor: '#00ffff',
		rainColorSource: 'manual',
		rainColorMode: 'solid',
		rainParticleType: 'lines',
		rainLength: 0.1,
		rainWidth: 0.0012,
		rainBlur: 0.002,
		rainSpeed: 1.2,
		rainVariation: 0.3,
		performanceMode: 'medium',
		audioSensitivity: 1.2,
		audioSmoothing: 0.75
	},

	rainyNight: {
		filterTargets: ['background'],
		filterOpacity: 1,
		filterBrightness: 1,
		filterContrast: 1,
		filterSaturation: 1,
		filterBlur: 0,
		filterHueRotate: 0,
		rgbShift: 0.003,
		scanlineIntensity: 0.14,
		scanlineMode: 'always',
		scanlineSpacing: 680,
		scanlineThickness: 1.3,
		parallaxStrength: 0.02,
		spectrumEnabled: true,
		spectrumInnerRadius: 70,
		spectrumBarCount: 96,
		spectrumBarWidth: 2,
		spectrumMinHeight: 2,
		spectrumMaxHeight: 90,
		spectrumOpacity: 0.6,
		spectrumGlowIntensity: 0.6,
		spectrumShadowBlur: 14,
		spectrumPrimaryColor: '#60a5fa',
		spectrumSecondaryColor: '#a5f3fc',
		spectrumColorSource: 'manual',
		spectrumColorMode: 'gradient',
		spectrumBandMode: 'full',
		spectrumShape: 'blocks',
		spectrumMode: 'radial',
		spectrumLinearOrientation: 'horizontal',
		spectrumRadialShape: 'circle',
		spectrumRadialAngle: 0,
		spectrumMirror: false,
		spectrumPeakHold: false,
		spectrumPeakDecay: 0.004,
		spectrumRotationSpeed: -0.05,
		spectrumSmoothing: 0.85,
		logoEnabled: false,
		logoBaseSize: 75,
		logoPositionX: 0,
		logoPositionY: 0,
		logoBandMode: 'kick',
		logoReactiveScaleIntensity: 0.3,
		logoReactivitySpeed: 0.2,
		logoAttack: 0.65,
		logoRelease: 0.08,
		logoMinScale: 1,
		logoMaxScale: 1.55,
		logoPunch: 0.22,
		logoPeakWindow: 2.8,
		logoPeakFloor: 0.2,
		logoGlowColor: '#60a5fa',
		logoGlowColorSource: 'manual',
		logoGlowBlur: 25,
		logoShadowEnabled: true,
		logoShadowColor: '#60a5fa',
		logoShadowColorSource: 'manual',
		logoShadowBlur: 35,
		logoBackdropEnabled: true,
		logoBackdropColor: '#000818',
		logoBackdropColorSource: 'manual',
		logoBackdropOpacity: 0.55,
		logoBackdropPadding: 18,
		particlesEnabled: true,
		particleLayerMode: 'background',
		particleColor1: '#60a5fa',
		particleColor2: '#a5f3fc',
		particleColorSource: 'manual',
		particleColorMode: 'gradient',
		particleSizeMin: 1,
		particleSizeMax: 2,
		particleOpacity: 0.45,
		particleGlow: false,
		particleGlowStrength: 0.2,
		particleFilterBrightness: 1,
		particleFilterContrast: 1,
		particleFilterSaturation: 1,
		particleFilterBlur: 0,
		particleFilterHueRotate: 0,
		particleRotationIntensity: 0.35,
		particleRotationDirection: 'counterclockwise',
		particleFadeInOut: true,
		particleAudioReactive: false,
		particleAudioSizeBoost: 1.0,
		particleAudioOpacityBoost: 0.1,
		particleCount: 30,
		particleSpeed: 0.35,
		rainEnabled: true,
		rainIntensity: 0.7,
		rainDropCount: 70,
		rainAngle: 15,
		rainMeshRotationZ: 0,
		rainColor: '#8ab4d4',
		rainColorSource: 'manual',
		rainColorMode: 'solid',
		rainParticleType: 'lines',
		rainLength: 0.14,
		rainWidth: 0.0015,
		rainBlur: 0.002,
		rainSpeed: 1.0,
		rainVariation: 0.45,
		performanceMode: 'medium',
		audioSensitivity: 0.9,
		audioSmoothing: 0.88
	}
};

export const PRESET_LABELS: Record<PresetKey, string> = {
	softDream: 'Soft Dream',
	cyberPop: 'Cyber Pop',
	rainyNight: 'Rainy Night'
};

const PRESET_EXCLUDED_KEYS = new Set<keyof WallpaperState>([
	'activePreset',
	'activeImageId',
	'audioCaptureState',
	'audioPaused',
	'audioReactive',
	'sceneSlots',
	'activeSceneSlotId',
	'particlesProfileSlots',
	'rainProfileSlots',
	'looksProfileSlots',
	'lightsProfileSlots',
	'cameraFxProfileSlots',
	'trackTitleProfileSlots',
	'backgroundProfileSlots',
	'backgroundImages',
	'globalBackgroundId',
	'globalBackgroundUrl',
	'globalBackgroundScale',
	'globalBackgroundPositionX',
	'globalBackgroundPositionY',
	'globalBackgroundFitMode',
	'globalBackgroundOpacity',
	'globalBackgroundBrightness',
	'globalBackgroundContrast',
	'globalBackgroundSaturation',
	'globalBackgroundBlur',
	'globalBackgroundHueRotate',
	'controlPanelAnchor',
	'customPresets',
	'layerZIndices',
	'imageIds',
	'imageUrl',
	'imageUrls',
	'isPresetDirty',
	'language',
	'logoProfileSlots',
	'logoId',
	'logoUrl',
	'motionPaused',
	'overlays',
	'selectedOverlayId',
	'showFps',
	'spectrumProfileSlots',
	'visualTransition'
]);

const PRESET_STATE_KEYS = (
	Object.keys(DEFAULT_STATE) as (keyof WallpaperState)[]
).filter(key => !PRESET_EXCLUDED_KEYS.has(key));

export function isBuiltInPresetKey(value: string): value is PresetKey {
	return value in presets;
}

export function extractPresetValues(state: WallpaperState): Preset {
	const values = {} as Record<string, unknown>;
	for (const key of PRESET_STATE_KEYS) {
		values[key] = state[key];
	}
	return values as Preset;
}

export function resolvePreset(id: string, customPresets: CustomPresetsMap) {
	if (isBuiltInPresetKey(id)) {
		return {
			id,
			kind: 'builtin' as const,
			name: PRESET_LABELS[id],
			values: presets[id]
		};
	}

	const customPreset = customPresets[id];
	if (!customPreset) return null;

	return {
		id: customPreset.id,
		kind: 'custom' as const,
		name: customPreset.name,
		values: customPreset.values
	};
}

export function getPresetName(
	id: string,
	customPresets: CustomPresetsMap
): string {
	return resolvePreset(id, customPresets)?.name ?? 'Custom';
}

export function doesStateMatchPreset(state: WallpaperState): boolean {
	const preset = resolvePreset(state.activePreset, state.customPresets);
	if (!preset) return true;

	return Object.entries(preset.values).every(([key, value]) => {
		const current = (state as Record<string, unknown>)[key];
		if (Array.isArray(value) && Array.isArray(current)) {
			return (
				value.length === current.length &&
				value.every((item, index) => current[index] === item)
			);
		}
		return current === value;
	});
}

export function createCustomPresetId(): string {
	const uuid = globalThis.crypto?.randomUUID?.();
	return `custom:${uuid ?? `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`}`;
}
