import type { WallpaperState } from '@/types/wallpaper';

export type MainTabId =
	| 'scene'
	| 'spectrum'
	| 'looks'
	| 'layers'
	| 'motion'
	| 'audio'
	| 'advanced';

export type AdvancedSubTab =
	| 'track'
	| 'lyrics'
	| 'logo'
	| 'diagnostics'
	| 'editor'
	| 'export'
	| 'perf'
	| 'calibration';

export const LEGACY_TAB_KEYS: Record<string, (keyof WallpaperState)[]> = {
	layers: ['layerZIndices'],
	presets: [
		'imageScale',
		'imagePositionX',
		'imagePositionY',
		'imageBassReactive',
		'backgroundImageEnabled',
		'imageOpacity',
		'imageAudioSmoothing',
		'imageOpacityReactive',
		'imageOpacityReactiveAmount',
		'imageOpacityReactiveInvert',
		'imageOpacityReactiveThreshold',
		'imageOpacityReactiveSoftness',
		'imageBlurReactive',
		'imageBlurReactiveAmount',
		'imageBlurReactiveInvert',
		'imageBlurReactiveThreshold',
		'imageBlurReactiveSoftness',
		'imageBassScaleIntensity',
		'imageAudioReactiveDecay',
		'imageBassAttack',
		'imageBassRelease',
		'imageBassReactivitySpeed',
		'imageBassPeakWindow',
		'imageBassPeakFloor',
		'imageBassPunch',
		'imageBassReactiveScaleIntensity',
		'imageAudioChannel',
		'imageFitMode',
		'imageMirror',
		'imageMirrorFill',
		'imageMirrorFillInvert',
		'imageMirrorFillCount',
		'imageRotation',
		'parallaxStrength',
		'globalBackgroundEnabled',
		'globalBackgroundScale',
		'globalBackgroundPositionX',
		'globalBackgroundPositionY',
		'globalBackgroundFitMode',
		'globalBackgroundOpacity',
		'globalBackgroundBrightness',
		'globalBackgroundContrast',
		'globalBackgroundSaturation',
		'globalBackgroundBlur',
		'globalBackgroundHueRotate',
		'slideshowEnabled',
		'slideshowInterval',
		'slideshowTransitionDuration',
		'slideshowTransitionType',
		'slideshowTransitionIntensity',
		'slideshowTransitionAudioDrive',
		'slideshowTransitionAudioChannel',
		'slideshowTransitionAudioSmoothing',
		'slideshowAudioCheckpointsEnabled',
		'slideshowTrackChangeSyncEnabled'
	],
	filters: [
		'filterTargets',
		'filterOpacity',
		'filterBrightness',
		'filterContrast',
		'filterSaturation',
		'filterBlur',
		'filterHueRotate',
		'filterVignette',
		'filterBloom',
		'filterLumaThreshold',
		'filterLensWarp',
		'filterHeatDistortion',
		'activeFilterLookId',
		'scanlinesEnabled',
		'scanlineIntensity',
		'scanlineMode',
		'scanlineSpacing',
		'scanlineThickness',
		'rgbShift',
		'noiseIntensity',
		'rgbShiftAudioReactive',
		'rgbShiftAudioSensitivity',
		'rgbShiftAudioChannel',
		'rgbShiftAudioSmoothing',
		'rgbShiftAudioAttack',
		'rgbShiftAudioRelease',
		'rgbShiftAudioReactivitySpeed',
		'rgbShiftAudioPeakWindow',
		'rgbShiftAudioPeakFloor',
		'rgbShiftAudioPunch'
	],
	audio: [
		'audioPaused',
		'motionPaused',
		'fftSize',
		'audioAutoKickThreshold',
		'audioAutoSwitchHoldMs'
	],
	track: [
		'trackMetadataMode',
		'trackMetadataAutoSource',
		'trackManualArtist',
		'trackManualTitle',
		'nowPlayingMode',
		'nowPlayingCoverEnabled',
		'nowPlayingArtistEnabled',
		'nowPlayingProgressEnabled',
		'nowPlayingScale',
		'nowPlayingAccentColor',
		'nowPlayingAccentColorSource',
		'nowPlayingTextTreatment',
		'audioTrackTitleLayoutMode',
		'audioTrackTitleFontStyle',
		'audioTrackTitleUppercase',
		'audioTrackTitleEnabled',
		'audioTrackTitlePositionX',
		'audioTrackTitlePositionY',
		'audioTrackTitleFontSize',
		'audioTrackTitleLetterSpacing',
		'audioTrackTitleWidth',
		'audioTrackTitleOpacity',
		'audioTrackTitleScrollSpeed',
		'audioTrackTitleRgbShift',
		'audioTrackTitleTextColorSource',
		'audioTrackTitleTextColor',
		'audioTrackTitleStrokeColorSource',
		'audioTrackTitleStrokeColor',
		'audioTrackTitleStrokeWidth',
		'audioTrackTitleGlowColorSource',
		'audioTrackTitleGlowColor',
		'audioTrackTitleGlowBlur',
		'audioTrackTitleGlowReach',
		'audioTrackTitleBackdropEnabled',
		'audioTrackTitleBackdropColorSource',
		'audioTrackTitleBackdropColor',
		'audioTrackTitleBackdropOpacity',
		'audioTrackTitleBackdropPadding',
		'audioTrackTitleFilterBrightness',
		'audioTrackTitleFilterContrast',
		'audioTrackTitleFilterSaturation',
		'audioTrackTitleFilterBlur',
		'audioTrackTitleFilterHueRotate',
		'audioTrackTimeEnabled',
		'audioTrackTimePositionX',
		'audioTrackTimePositionY',
		'audioTrackTimeFontStyle',
		'audioTrackTimeFontSize',
		'audioTrackTimeLetterSpacing',
		'audioTrackTimeOpacity',
		'audioTrackTimeRgbShift',
		'audioTrackTimeTextColorSource',
		'audioTrackTimeTextColor',
		'audioTrackTimeStrokeColorSource',
		'audioTrackTimeStrokeColor',
		'audioTrackTimeStrokeWidth',
		'audioTrackTimeGlowColorSource',
		'audioTrackTimeGlowColor',
		'audioTrackTimeGlowBlur',
		'audioTrackTimeGlowReach',
		'audioTrackTimeFilterBrightness',
		'audioTrackTimeFilterContrast',
		'audioTrackTimeFilterSaturation',
		'audioTrackTimeFilterBlur',
		'audioTrackTimeFilterHueRotate'
	],
	lyrics: [
		'audioLyricsEnabled',
		'audioLyricsLayoutMode',
		'audioLyricsUppercase',
		'audioLyricsPositionX',
		'audioLyricsPositionY',
		'audioLyricsWidth',
		'audioLyricsFontStyle',
		'audioLyricsFontSize',
		'audioLyricsLetterSpacing',
		'audioLyricsLineHeight',
		'audioLyricsVisibleLineCount',
		'audioLyricsShowTranslation',
		'audioLyricsOpacity',
		'audioLyricsInactiveOpacity',
		'audioLyricsTimeOffsetMs',
		'audioLyricsActiveColorSource',
		'audioLyricsActiveColor',
		'audioLyricsInactiveColorSource',
		'audioLyricsInactiveColor',
		'audioLyricsTextTreatment',
		'audioLyricsStrokeColorSource',
		'audioLyricsStrokeColor',
		'audioLyricsStrokeWidth',
		'audioLyricsGlowColorSource',
		'audioLyricsGlowColor',
		'audioLyricsGlowBlur',
		'audioLyricsGlowReach',
		'audioLyricsTransitionIn',
		'audioLyricsTransitionOut',
		'audioLyricsActiveAnimation',
		'audioLyricsAnimationDurationMs',
		'audioLyricsBackdropEnabled',
		'audioLyricsBackdropColorSource',
		'audioLyricsBackdropColor',
		'audioLyricsBackdropOpacity',
		'audioLyricsBackdropPadding',
		'audioLyricsBackdropRadius'
	],
	spectrum: [
		'spectrumEnabled',
		'spectrumMainVisible',
		'spectrumMode',
		'spectrumLinearOrientation',
		'spectrumLinearDirection',
		'spectrumRadialShape',
		'spectrumRadialAngle',
		'spectrumRadialSharpness',
		'spectrumFigureRotationSpeed',
		'spectrumRadialFitLogo',
		'spectrumFollowLogo',
		'spectrumLogoGap',
		'spectrumInstances',
		'spectrumColorSource',
		'spectrumShape',
		'spectrumSpan',
		'spectrumBarCount',
		'spectrumBarWidth',
		'spectrumMinHeight',
		'spectrumMaxHeight',
		'spectrumSmoothing',
		'spectrumAudioSmoothing',
		'spectrumOpacity',
		'spectrumGlowIntensity',
		'spectrumGlowReach',
		'spectrumGlowAudioAmount',
		'spectrumShadowBlur',
		'spectrumPrimaryColor',
		'spectrumSecondaryColor',
		'spectrumColorMode',
		'spectrumManualGlow',
		'spectrumManualGlowMode',
		'spectrumGlowColorSource',
		'spectrumGlowColorMode',
		'spectrumGlowPrimaryColor',
		'spectrumGlowSecondaryColor',
		'spectrumPixelate',
		'spectrumPixelateScale',
		'spectrumLedCellSize',
		'spectrumLedCellGap',
		'spectrumLedAngle',
		'spectrumLedShape',
		'spectrumRgbSplit',
		'spectrumRgbSplitAmount',
		'spectrumNeonCore',
		'spectrumNeonCoreIntensity',
		'spectrumNeonCoreWidth',
		'spectrumGradientFlow',
		'spectrumGradientFlowSpeed',
		'spectrumGradientFlowAudio',
		'spectrumGradientFlowDirection',
		'spectrumPeakSparks',
		'spectrumPeakSparksAmount',
		'spectrumPeakSparksSize',
		'spectrumPeakSparksThreshold',
		'spectrumEchoTrace',
		'spectrumEchoTraceCount',
		'spectrumEchoTraceOpacity',
		'spectrumEchoTraceOffset',
		'spectrumEchoTraceDecay',
		'spectrumBandMode',
		'spectrumWaveFillOpacity',
		'spectrumMirror',
		'spectrumPeakHold',
		'spectrumPeakDecay',
		'spectrumRotationSpeed',
		'spectrumRotationDrive',
		'spectrumRotationAudioAmount',
		'spectrumRotationChannel',
		'spectrumRotationDirection',
		'spectrumRotationSmoothing',
		'spectrumRotationInvertOnLowEnergy',
		'spectrumRotationInvertThreshold',
		'spectrumRotationInvertHoldMs',
		'spectrumScale',
		'spectrumInnerRadius',
		'spectrumPositionX',
		'spectrumPositionY',
		'spectrumTunnelRingCount',
		'spectrumTunnelDepthFalloff',
		'spectrumTunnelRingSpacing',
		'spectrumTunnelWallOpacity',
		'spectrumTunnelPulseStrength',
		// Frame memory + reactivity expressiveness (added during the
		// calibration sprint — without these in the section list the
		// project export/import would silently drop them).
		'spectrumFrameMemoryEnabled',
		'spectrumFrameHistoryDepth',
		'spectrumGainExpressiveness',
		'spectrumEnvelopeAttack',
		'spectrumEnvelopeRelease',
		'spectrumEnvelopeReactivitySpeed',
		'spectrumEnvelopePeakWindow',
		'spectrumEnvelopePeakFloor',
		'spectrumEnvelopePunch',
		// Tunnel alternating rotation toggle
		'spectrumTunnelAlternateRotation',
		'spectrumLiquidLayer1Opacity',
		'spectrumLiquidLayer2Opacity',
		'spectrumLiquidLayer3Opacity',
		'spectrumLiquidLayer1Amp',
		'spectrumLiquidLayer2Amp',
		'spectrumLiquidLayer3Amp',
		'spectrumLiquidLayer1Fill',
		'spectrumLiquidLayer2Fill',
		'spectrumLiquidLayer3Fill',
		'spectrumLiquidLayer1Speed',
		'spectrumLiquidLayer2Speed',
		'spectrumLiquidLayer3Speed',
		'spectrumLiquidLayer1RotationSpeed',
		'spectrumLiquidLayer2RotationSpeed',
		'spectrumLiquidLayer3RotationSpeed',
		'spectrumLiquidLayer1Shape',
		'spectrumLiquidLayer2Shape',
		'spectrumLiquidLayer3Shape',
		'spectrumLiquidLayer1RigidShape',
		'spectrumLiquidLayer2RigidShape',
		'spectrumLiquidLayer3RigidShape',
		'spectrumSpiralTurns',
		'spectrumSpiralOuterRadius',
		'spectrumSpiralTightness',
		'spectrumSpiralShape',
		'spectrumSpiralLogarithmic',
		'spectrumSpiralGradientStroke',
		'spectrumSpiralArms',
		'spectrumSpiralAudioTurns',
		'spectrumSpiralDotShape',
		'spectrumSpiralStrokeWidth',
		'spectrumOscilloscopeLineWidth',
		'spectrumOscilloscopeScrollSpeed',
		'spectrumOscilloscopeReactiveWidth',
		'spectrumOscilloscopePhosphor',
		'spectrumOscilloscopePhosphorDecay',
		'spectrumOscilloscopeGrid',
		'spectrumOscilloscopeGridDivisions',
		// Manual keyboard control (v64)
		'spectrumDriveMode',
		'spectrumManualSections',
		'spectrumManualAddWeight',
		'spectrumManualAttack',
		'spectrumManualRelease',
		'spectrumManualBindings',
		'showSpectrumManualHud'
	],
	logo: [
		'logoEnabled',
		'logoBaseSize',
		'logoPositionX',
		'logoPositionY',
		'logoAudioSmoothing',
		'logoAudioSensitivity',
		'logoReactiveScaleIntensity',
		'logoBandMode',
		'logoReactivitySpeed',
		'logoAttack',
		'logoRelease',
		'logoMinScale',
		'logoMaxScale',
		'logoPunch',
		'logoPeakWindow',
		'logoPeakFloor',
		// Glow ring master toggle (v63 — was missing from export selection)
		'logoGlowEnabled',
		'logoGlowColorSource',
		'logoGlowColor',
		'logoGlowBlur',
		'logoGlowReach',
		'logoGlowAudioAmount',
		'logoShadowEnabled',
		'logoShadowColorSource',
		'logoShadowColor',
		'logoShadowBlur',
		'logoBackdropEnabled',
		'logoBackdropColorSource',
		'logoBackdropColor',
		'logoBackdropOpacity',
		'logoBackdropPadding',
		// Image rotation (v63)
		'logoRotationSpeed'
	],
	diagnostics: [
		'showBackgroundScaleMeter',
		'showAutoZoomDebug',
		'showSpectrumDiagnosticsHud',
		'showLogoDiagnosticsHud',
		'diagnosticsHudPositionX',
		'diagnosticsHudPositionY'
	],
	particles: [
		'particlesEnabled',
		'particleLayerMode',
		'particleCount',
		'particleSpeed',
		'particleShape',
		'particleColorSource',
		'particleColorMode',
		'particleColor1',
		'particleColor2',
		'particleOpacity',
		'particleFilterBrightness',
		'particleFilterContrast',
		'particleFilterSaturation',
		'particleFilterBlur',
		'particleFilterHueRotate',
		'particleRotationIntensity',
		'particleRotationDirection',
		'particleSizeMin',
		'particleSizeMax',
		'particleGlow',
		'particleGlowStrength',
		'particleGlowReach',
		'particleGlowAudioAmount',
		'particleFadeInOut',
		'particleAudioReactive',
		'particleAudioChannel',
		'particleAudioSmoothing',
		'particleAudioSizeBoost',
		'particleAudioOpacityBoost',
		'particleAudioAttack',
		'particleAudioRelease',
		'particleAudioReactivitySpeed',
		'particleAudioPeakWindow',
		'particleAudioPeakFloor',
		'particleAudioPunch',
		'particleAudioDriftEnabled',
		'particleAudioDriftAngle',
		'particleAudioDriftAmount',
		'particleAudioDriftBase',
		'particleAudioDriftChannel',
		'particleAudioDriftThreshold',
		'particleAudioDriftRelease',
		'particleAudioDriftMode',
		'particleAudioDriftInvertOnLowEnergy',
		'particleDepthFlowEnabled',
		'particleDepthFlowAmount',
		'particleDepthFlowDirection',
		'particleDepthFlowChannel',
		'particleDepthFlowThreshold',
		'particleDepthFlowSensitivity',
		'particleDepthFlowAttack',
		'particleDepthFlowRelease',
		'particleDepthFlowSpeed',
		'particleDepthFlowSpread',
		'particleDepthFlowFocusX',
		'particleDepthFlowFocusY',
		'particleDepthFlowMode',
		'particleDepthFlowSpawnOrigin',
		'particleDepthFlowInvertFocusOnLowEnergy',
		'particleDepthFlowInvertFocusAxis',
		'particleDepthFlowWindInfluence',
		'particleLifetime'
	],
	rain: [
		'rainEnabled',
		'rainIntensity',
		'rainDropCount',
		'rainAngle',
		'rainMeshRotationZ',
		'rainColorSource',
		'rainColor',
		'rainColorMode',
		'rainParticleType',
		'rainLength',
		'rainWidth',
		'rainBlur',
		'rainSpeed',
		'rainVariation'
	],
	stageFx: [
		'stageLightsEnabled',
		'stageLightsIntensity',
		'stageLightsBeamCount',
		'stageLightsMinBeamCount',
		'stageLightsMaxBeamCount',
		'stageLightsBeamWidth',
		'stageLightsBeamLength',
		'stageLightsSoftness',
		'stageLightsSpeed',
		'stageLightsFixedMotion',
		'stageLightsColorSource',
		'stageLightsColor',
		'stageLightsAudioReactive',
		'stageLightsAudioChannel',
		'stageLightsAudioAmount',
		'stageLightsAudioOscillationAmount',
		'stageLightsAudioHoldMs',
		'stageLightsAudioDecay',
		'stageLightsAudioGateEnabled',
		'stageLightsPeakFlash',
		'stageLightsPeakThreshold',
		'stageLightsBandThresholds',
		'stageLightsOpacity',
		'stageLightsBlendMode',
		'stageLightsOrigin',
		'stageLightsMovementMode',
		'stageLightsInvertDirection',
		'stageLightsMirrorDirections',
		'flashLightEnabled',
		'flashLightIntensity',
		'flashLightColorSource',
		'flashLightColor',
		'flashLightSoftness',
		'flashLightBrightness',
		'flashLightDecay',
		'flashLightAudioChannel',
		'flashLightThreshold',
		'flashLightBandThresholds',
		'flashLightSensitivity',
		'flashLightRetriggerMs',
		'flashLightShape',
		'flashLightBlendMode',
		'cameraFxEnabled',
		'cameraMotionEnabled',
		'cameraMotionMode',
		'cameraMotionAmount',
		'cameraMotionSpeed',
		'cameraMotionDrive',
		'cameraMotionAudioInfluence',
		'cameraMotionAudioChannel',
		'cameraMotionDirection',
		'cameraMotionTarget',
		'cameraMotionTargets',
		'cameraShakeEnabled',
		'cameraShakeAmount',
		'cameraShakeDecay',
		'cameraShakeThreshold',
		'cameraShakeBandThresholds',
		'cameraShakeTargets',
		'cameraShakeSensitivity',
		'cameraShakeRetriggerMs',
		'cameraShakeChannel',
		'cameraShakeMode',
		'cameraShakeFrequency',
		'cameraShakeRoughness'
	],
	editor: [
		'showFps',
		'controlPanelAnchor',
		'fpsOverlayAnchor',
		'layoutResponsiveEnabled',
		'layoutBackgroundReframeEnabled',
		'layoutReferenceWidth',
		'layoutReferenceHeight',
		'editorTheme',
		'editorThemeColorSource',
		'editorCornerRadius',
		'editorControlCornerRadius',
		'editorManualAccentColor',
		'editorManualSecondaryColor',
		'editorManualBackdropColor',
		'editorManualTextPrimaryColor',
		'editorManualTextSecondaryColor',
		'editorManualBackdropOpacity',
		'editorManualBlurPx',
		'editorManualSurfaceOpacity',
		'quickActionsEnabled',
		'quickActionsPositionX',
		'quickActionsPositionY',
		'quickActionsLauncherPositionX',
		'quickActionsLauncherPositionY',
		'quickActionsBackdropOpacity',
		'quickActionsBlurPx',
		'quickActionsScale',
		'quickActionsLauncherSize',
		'quickActionsColorSource',
		'quickActionsManualAccentColor',
		'quickActionsManualSecondaryColor',
		'quickActionsManualBackdropColor',
		'quickActionsManualTextPrimaryColor',
		'quickActionsManualTextSecondaryColor',
		'quickActionsManualSurfaceOpacity'
	],
	overlays: [],
	export: ['offlineExportResolutionId', 'offlineExportFps'],
	perf: ['performanceMode']
};

export function resolveCanvasInteractionTab(
	main: MainTabId,
	advanced: AdvancedSubTab
): string | null {
	switch (main) {
		case 'scene':
			return 'presets';
		case 'spectrum':
			return 'spectrum';
		case 'looks':
			return 'filters';
		case 'layers':
			return 'layers';
		case 'motion':
			return 'particles';
		case 'audio':
			return 'audio';
		case 'advanced':
			return advanced;
		default:
			return null;
	}
}

export const MAIN_TAB_RESET_KEYS: Record<MainTabId, (keyof WallpaperState)[]> =
	{
		scene: [],
		spectrum: LEGACY_TAB_KEYS.spectrum ?? [],
		looks: LEGACY_TAB_KEYS.filters ?? [],
		layers: [
			...(LEGACY_TAB_KEYS.presets ?? []),
			...(LEGACY_TAB_KEYS.layers ?? [])
		],
		motion: [
			...(LEGACY_TAB_KEYS.particles ?? []),
			...(LEGACY_TAB_KEYS.rain ?? []),
			...(LEGACY_TAB_KEYS.stageFx ?? [])
		],
		audio: LEGACY_TAB_KEYS.audio ?? [],
		advanced: []
	};

export const ADVANCED_RESET_KEYS: Record<
	AdvancedSubTab,
	(keyof WallpaperState)[]
> = {
	track: LEGACY_TAB_KEYS.track ?? [],
	lyrics: LEGACY_TAB_KEYS.lyrics ?? [],
	logo: LEGACY_TAB_KEYS.logo ?? [],
	diagnostics: LEGACY_TAB_KEYS.diagnostics ?? [],
	editor: LEGACY_TAB_KEYS.editor ?? [],
	export: LEGACY_TAB_KEYS.export ?? [],
	perf: LEGACY_TAB_KEYS.perf ?? [],
	calibration: ['calibrationRangeOverrides', 'calibrationProfileSlots']
};

function partitionEditorKeysForOverlay(editorKeys: (keyof WallpaperState)[]): {
	hud: (keyof WallpaperState)[];
	editorUi: (keyof WallpaperState)[];
} {
	const hud: (keyof WallpaperState)[] = [];
	const editorUi: (keyof WallpaperState)[] = [];
	for (const k of editorKeys) {
		if (String(k).startsWith('quickActions')) {
			hud.push(k);
		} else {
			editorUi.push(k);
		}
	}
	return { hud, editorUi };
}

const { hud: editorOverlayHudKeys, editorUi: editorOverlayEditorUiKeys } =
	partitionEditorKeysForOverlay(LEGACY_TAB_KEYS.editor ?? []);

/** Reset keys for the full-screen editor grid (HUD vs editor UI split). */
export const EDITOR_OVERLAY_TAB_KEYS: Record<string, (keyof WallpaperState)[]> =
	{
		...LEGACY_TAB_KEYS,
		editor: editorOverlayEditorUiKeys,
		hud: editorOverlayHudKeys
	};
