import { useShallow } from 'zustand/react/shallow';
import { useWallpaperStore } from '@/store/wallpaperStore';

export function useQuickActionsState() {
	return useWallpaperStore(
		useShallow(state => ({
			quickActionsEnabled: state.quickActionsEnabled,
			quickActionsPositionX: state.quickActionsPositionX,
			quickActionsPositionY: state.quickActionsPositionY,
			quickActionsLauncherPositionX: state.quickActionsLauncherPositionX,
			quickActionsLauncherPositionY: state.quickActionsLauncherPositionY,
			quickActionsBackdropOpacity: state.quickActionsBackdropOpacity,
			quickActionsBlurPx: state.quickActionsBlurPx,
			quickActionsScale: state.quickActionsScale,
			quickActionsLauncherSize: state.quickActionsLauncherSize,
			layoutResponsiveEnabled: state.layoutResponsiveEnabled,
			layoutReferenceWidth: state.layoutReferenceWidth,
			layoutReferenceHeight: state.layoutReferenceHeight,
			quickActionsColorSource: state.quickActionsColorSource,
			editorThemeColorSource: state.editorThemeColorSource,
			spectrumColorSource: state.spectrumColorSource,

			logoGlowColorSource: state.logoGlowColorSource,
			logoShadowColorSource: state.logoShadowColorSource,
			logoBackdropColorSource: state.logoBackdropColorSource,
			particleColorSource: state.particleColorSource,
			rainColorSource: state.rainColorSource,
			audioTrackTitleTextColorSource:
				state.audioTrackTitleTextColorSource,
			audioTrackTitleStrokeColorSource:
				state.audioTrackTitleStrokeColorSource,
			audioTrackTitleGlowColorSource:
				state.audioTrackTitleGlowColorSource,
			audioTrackTitleBackdropColorSource:
				state.audioTrackTitleBackdropColorSource,
			audioTrackTimeTextColorSource: state.audioTrackTimeTextColorSource,
			audioTrackTimeStrokeColorSource:
				state.audioTrackTimeStrokeColorSource,
			audioTrackTimeGlowColorSource: state.audioTrackTimeGlowColorSource,
			syncAllColorSources: state.syncAllColorSources,
			setEditorShellColorSource: state.setEditorShellColorSource,
			setSpectrumColorSources: state.setSpectrumColorSources,
			setLogoColorSources: state.setLogoColorSources,
			setMotionColorSources: state.setMotionColorSources,
			setTrackTitleColorSources: state.setTrackTitleColorSources,
			quickActionsManualAccentColor: state.quickActionsManualAccentColor,
			quickActionsManualSecondaryColor:
				state.quickActionsManualSecondaryColor,
			quickActionsManualBackdropColor:
				state.quickActionsManualBackdropColor,
			quickActionsManualTextPrimaryColor:
				state.quickActionsManualTextPrimaryColor,
			quickActionsManualTextSecondaryColor:
				state.quickActionsManualTextSecondaryColor,
			quickActionsManualSurfaceOpacity:
				state.quickActionsManualSurfaceOpacity,
			quickActionsManualItemOpacity: state.quickActionsManualItemOpacity,
			editorTheme: state.editorTheme,
			editorCornerRadius: state.editorCornerRadius,
			editorControlCornerRadius: state.editorControlCornerRadius,
			logoUrl: state.logoUrl,
			logoId: state.logoId,
			logoVariantMode: state.logoVariantMode,
			setLogoVariantMode: state.setLogoVariantMode,
			restoreFactoryLogo: state.restoreFactoryLogo,
			backgroundImages: state.backgroundImages,
			activeImageId: state.activeImageId,
			setActiveImageId: state.setActiveImageId,
			setlists: state.setlists,
			activeSetlistId: state.activeSetlistId,
			audioTracks: state.audioTracks,
			activeAudioTrackId: state.activeAudioTrackId,
			spectrumProfileSlots: state.spectrumProfileSlots,
			spectrumSecondProfileSlots: state.spectrumSecondProfileSlots,
			loadSpectrumProfileSlot: state.loadSpectrumProfileSlot,
			looksProfileSlots: state.looksProfileSlots,
			loadLooksProfileSlot: state.loadLooksProfileSlot,
			particlesProfileSlots: state.particlesProfileSlots,
			loadParticlesProfileSlot: state.loadParticlesProfileSlot,
			rainProfileSlots: state.rainProfileSlots,
			loadRainProfileSlot: state.loadRainProfileSlot,
			lightsProfileSlots: state.lightsProfileSlots,
			loadLightsProfileSlot: state.loadLightsProfileSlot,
			cameraFxProfileSlots: state.cameraFxProfileSlots,
			loadCameraFxProfileSlot: state.loadCameraFxProfileSlot,
			logoProfileSlots: state.logoProfileSlots,
			loadLogoProfileSlot: state.loadLogoProfileSlot,
			logoPositionX: state.logoPositionX,
			logoPositionY: state.logoPositionY,
			setLogoPositionX: state.setLogoPositionX,
			setLogoPositionY: state.setLogoPositionY,
			trackTitleProfileSlots: state.trackTitleProfileSlots,
			loadTrackTitleProfileSlot: state.loadTrackTitleProfileSlot,
			backgroundImageEnabled: state.backgroundImageEnabled,
			setBackgroundImageEnabled: state.setBackgroundImageEnabled,
			globalBackgroundEnabled: state.globalBackgroundEnabled,
			setGlobalBackgroundEnabled: state.setGlobalBackgroundEnabled,
			slideshowEnabled: state.slideshowEnabled,
			setSlideshowEnabled: state.setSlideshowEnabled,
			spectrumEnabled: state.spectrumEnabled,
			setSpectrumEnabled: state.setSpectrumEnabled,
			logoEnabled: state.logoEnabled,
			setLogoEnabled: state.setLogoEnabled,
			audioTrackTitleEnabled: state.audioTrackTitleEnabled,
			setAudioTrackTitleEnabled: state.setAudioTrackTitleEnabled,
			audioTrackTimeEnabled: state.audioTrackTimeEnabled,
			setAudioTrackTimeEnabled: state.setAudioTrackTimeEnabled,
			particlesEnabled: state.particlesEnabled,
			setParticlesEnabled: state.setParticlesEnabled,
			particleLayerMode: state.particleLayerMode,
			setParticleLayerMode: state.setParticleLayerMode,
			rainEnabled: state.rainEnabled,
			setRainEnabled: state.setRainEnabled,
			overlays: state.overlays,
			updateOverlay: state.updateOverlay,
			motionPaused: state.motionPaused,
			setMotionPaused: state.setMotionPaused,
			stageLightsEnabled: state.stageLightsEnabled,
			setStageLightsEnabled: state.setStageLightsEnabled,
			flashLightEnabled: state.flashLightEnabled,
			setFlashLightEnabled: state.setFlashLightEnabled,
			cameraMotionEnabled: state.cameraMotionEnabled,
			setCameraMotionEnabled: state.setCameraMotionEnabled,
			cameraShakeEnabled: state.cameraShakeEnabled,
			setCameraShakeEnabled: state.setCameraShakeEnabled,
			imageBassReactive: state.imageBassReactive,
			setImageBassReactive: state.setImageBassReactive,
			imageMirror: state.imageMirror,
			setImageMirror: state.setImageMirror,
			imageMirrorFill: state.imageMirrorFill,
			setImageMirrorFill: state.setImageMirrorFill,
			imageOpacityReactive: state.imageOpacityReactive,
			setImageOpacityReactive: state.setImageOpacityReactive,
			particleAudioReactive: state.particleAudioReactive,
			setParticleAudioReactive: state.setParticleAudioReactive,
			particleGlow: state.particleGlow,
			setParticleGlow: state.setParticleGlow,
			particleFadeInOut: state.particleFadeInOut,
			setParticleFadeInOut: state.setParticleFadeInOut,
			particleAudioDriftEnabled: state.particleAudioDriftEnabled,
			setParticleAudioDriftEnabled: state.setParticleAudioDriftEnabled,
			particleDepthFlowEnabled: state.particleDepthFlowEnabled,
			setParticleDepthFlowEnabled: state.setParticleDepthFlowEnabled,
			spectrumMainVisible: state.spectrumMainVisible,
			setSpectrumMainVisible: state.setSpectrumMainVisible,
			spectrumMirror: state.spectrumMirror,
			setSpectrumMirror: state.setSpectrumMirror,
			spectrumPeakHold: state.spectrumPeakHold,
			setSpectrumPeakHold: state.setSpectrumPeakHold,
			spectrumPixelate: state.spectrumPixelate,
			spectrumInstances: state.spectrumInstances,
			setSpectrumInstanceEnabled: state.setSpectrumInstanceEnabled,
			updateSpectrumInstance: state.updateSpectrumInstance,
			patchSpectrumMain: state.patchSpectrumMain,
			activeSpectrumTarget: state.activeSpectrumTarget,
			setActiveSpectrumTarget: state.setActiveSpectrumTarget,
			logoShadowEnabled: state.logoShadowEnabled,
			setLogoShadowEnabled: state.setLogoShadowEnabled,
			logoBackdropEnabled: state.logoBackdropEnabled,
			setLogoBackdropEnabled: state.setLogoBackdropEnabled,
			audioTrackTitleBackdropEnabled:
				state.audioTrackTitleBackdropEnabled,
			setAudioTrackTitleBackdropEnabled:
				state.setAudioTrackTitleBackdropEnabled,
			rgbShiftAudioReactive: state.rgbShiftAudioReactive,
			setRgbShiftAudioReactive: state.setRgbShiftAudioReactive,
			audioCrossfadeEnabled: state.audioCrossfadeEnabled,
			setAudioCrossfadeEnabled: state.setAudioCrossfadeEnabled,
			audioAutoAdvance: state.audioAutoAdvance,
			setAudioAutoAdvance: state.setAudioAutoAdvance,
			audioFileLoop: state.audioFileLoop,
			setAudioFileLoop: state.setAudioFileLoop,
			audioReactive: state.audioReactive,
			setAudioReactive: state.setAudioReactive,
			mediaSessionEnabled: state.mediaSessionEnabled,
			setMediaSessionEnabled: state.setMediaSessionEnabled,
			audioTrackTitleUppercase: state.audioTrackTitleUppercase,
			setAudioTrackTitleUppercase: state.setAudioTrackTitleUppercase,
			slideshowAudioCheckpointsEnabled:
				state.slideshowAudioCheckpointsEnabled,
			setSlideshowAudioCheckpointsEnabled:
				state.setSlideshowAudioCheckpointsEnabled,
			slideshowTrackChangeSyncEnabled:
				state.slideshowTrackChangeSyncEnabled,
			setSlideshowTrackChangeSyncEnabled:
				state.setSlideshowTrackChangeSyncEnabled,
			slideshowManualTimestampsEnabled:
				state.slideshowManualTimestampsEnabled,
			setSlideshowManualTimestampsEnabled:
				state.setSlideshowManualTimestampsEnabled,
			slideshowResetPosition: state.slideshowResetPosition,
			setSlideshowResetPosition: state.setSlideshowResetPosition,
			spectrumFollowLogo: state.spectrumFollowLogo,
			setSpectrumFollowLogo: state.setSpectrumFollowLogo,
			spectrumRadialFitLogo: state.spectrumRadialFitLogo,
			setSpectrumRadialFitLogo: state.setSpectrumRadialFitLogo,

			showFps: state.showFps,
			setShowFps: state.setShowFps,
			sleepModeEnabled: state.sleepModeEnabled,
			setSleepModeEnabled: state.setSleepModeEnabled,
			layoutBackgroundReframeEnabled:
				state.layoutBackgroundReframeEnabled,
			setLayoutResponsiveEnabled: state.setLayoutResponsiveEnabled,
			setLayoutBackgroundReframeEnabled:
				state.setLayoutBackgroundReframeEnabled,
			setQuickActionsColorSource: state.setQuickActionsColorSource,
			setQuickActionsManualAccentColor:
				state.setQuickActionsManualAccentColor,
			setQuickActionsManualSecondaryColor:
				state.setQuickActionsManualSecondaryColor,
			setQuickActionsManualBackdropColor:
				state.setQuickActionsManualBackdropColor,
			setQuickActionsManualTextPrimaryColor:
				state.setQuickActionsManualTextPrimaryColor,
			setQuickActionsManualTextSecondaryColor:
				state.setQuickActionsManualTextSecondaryColor,
			setQuickActionsManualSurfaceOpacity:
				state.setQuickActionsManualSurfaceOpacity,
			setQuickActionsManualItemOpacity:
				state.setQuickActionsManualItemOpacity,
			performanceSafeEnabled: state.performanceSafeEnabled,
			setPerformanceSafeEnabled: state.setPerformanceSafeEnabled,
			virtualFoldersEnabled: state.virtualFoldersEnabled,
			setVirtualFoldersEnabled: state.setVirtualFoldersEnabled,
			showBackgroundScaleMeter: state.showBackgroundScaleMeter,
			setShowBackgroundScaleMeter: state.setShowBackgroundScaleMeter,
			showSpectrumDiagnosticsHud: state.showSpectrumDiagnosticsHud,
			setShowSpectrumDiagnosticsHud: state.setShowSpectrumDiagnosticsHud,
			showLogoDiagnosticsHud: state.showLogoDiagnosticsHud,
			setShowLogoDiagnosticsHud: state.setShowLogoDiagnosticsHud,
			enableDragMode: state.enableDragMode,
			setEnableDragMode: state.setEnableDragMode,
			activeTool: state.activeTool,
			setActiveTool: state.setActiveTool,
			setDragTool: state.setDragTool,
			showSetlistHud: state.showSetlistHud,
			setShowSetlistHud: state.setShowSetlistHud,
			setEditorTheme: state.setEditorTheme
		}))
	);
}

export type QuickActionsState = ReturnType<typeof useQuickActionsState>;
