import type { SlideshowTransitionType } from '@/types/wallpaper';

export const TRANSITION_TYPES = [
	'fade',
	'slide-left',
	'slide-right',
	'zoom-in',
	'blur-dissolve',
	'bars-horizontal',
	'bars-vertical',
	'rgb-shift',
	'distortion',
	'cross-zoom',
	'diagonal-wipe',
	'iris',
	'cross-zoom-out',
	'diagonal-wipe-reverse',
	'iris-close',
	'slide-up',
	'slide-down',
	'zoom-out',
	'wipe-left',
	'wipe-right',
	'wipe-up',
	'wipe-down',
	'spin-left',
	'spin-right',
	'diamond',
	'diamond-close',
	'curtain',
	'curtain-close',
	'checkerboard',
	'mosaic',
	'ripple',
	'wave',
	'squeeze-horizontal',
	'squeeze-vertical'
] as const satisfies readonly SlideshowTransitionType[];

export const TRANSITION_LABELS = {
	fade: 'transition_style_fade',
	'slide-left': 'transition_style_slide_left',
	'slide-right': 'transition_style_slide_right',
	'zoom-in': 'transition_style_zoom_in',
	'blur-dissolve': 'transition_style_blur_dissolve',
	'bars-horizontal': 'transition_style_bars_horizontal',
	'bars-vertical': 'transition_style_bars_vertical',
	'rgb-shift': 'transition_style_rgb_shift',
	distortion: 'transition_style_distortion',
	'cross-zoom': 'transition_style_cross_zoom',
	'diagonal-wipe': 'transition_style_diagonal_wipe',
	iris: 'transition_style_iris',
	'cross-zoom-out': 'transition_style_cross_zoom_out',
	'diagonal-wipe-reverse': 'transition_style_diagonal_wipe_reverse',
	'iris-close': 'transition_style_iris_close',
	'slide-up': 'transition_style_slide_up',
	'slide-down': 'transition_style_slide_down',
	'zoom-out': 'transition_style_zoom_out',
	'wipe-left': 'transition_style_wipe_left',
	'wipe-right': 'transition_style_wipe_right',
	'wipe-up': 'transition_style_wipe_up',
	'wipe-down': 'transition_style_wipe_down',
	'spin-left': 'transition_style_spin_left',
	'spin-right': 'transition_style_spin_right',
	diamond: 'transition_style_diamond',
	'diamond-close': 'transition_style_diamond_close',
	curtain: 'transition_style_curtain',
	'curtain-close': 'transition_style_curtain_close',
	checkerboard: 'transition_style_checkerboard',
	mosaic: 'transition_style_mosaic',
	ripple: 'transition_style_ripple',
	wave: 'transition_style_wave',
	'squeeze-horizontal': 'transition_style_squeeze_horizontal',
	'squeeze-vertical': 'transition_style_squeeze_vertical'
} as const satisfies Record<SlideshowTransitionType, string>;

export const TRANSITION_REVERSE: Partial<
	Record<SlideshowTransitionType, SlideshowTransitionType>
> = {
	'cross-zoom': 'cross-zoom-out',
	'cross-zoom-out': 'cross-zoom',
	'diagonal-wipe': 'diagonal-wipe-reverse',
	'diagonal-wipe-reverse': 'diagonal-wipe',
	iris: 'iris-close',
	'iris-close': 'iris',
	'slide-left': 'slide-right',
	'slide-right': 'slide-left',
	'slide-up': 'slide-down',
	'slide-down': 'slide-up',
	'zoom-in': 'zoom-out',
	'zoom-out': 'zoom-in',
	'wipe-left': 'wipe-right',
	'wipe-right': 'wipe-left',
	'wipe-up': 'wipe-down',
	'wipe-down': 'wipe-up',
	'spin-left': 'spin-right',
	'spin-right': 'spin-left',
	diamond: 'diamond-close',
	'diamond-close': 'diamond',
	curtain: 'curtain-close',
	'curtain-close': 'curtain'
};
